### ISSUE TITLE
add a silent mode

### ISSUE THREAD

**Issue by mdre** [FlowingCode/SimpleTimerAddon#2]
Hi Javier.

Would you consider adding a silent execution mode where the clock is not visible ?, so that only the timer event is generated and can react to it.
For example, to change a graph every x seconds. 

Thanks.

Marcelo

**Comment by mlopezFC** [comment]
We've added support for this, but please take into account [this issue](https://github.com/FlowingCode/SimpleTimerAddon/issues/4) that still needs to be fixed.

Regards.
