### ISSUE TITLE
$0.start is not a function error

### ISSUE THREAD

**Issue by paodb** [FlowingCode/SimpleTimerAddon#21]
From directory:

> Im getting a
> 
> ```
> (TypeError) : $0.start is not a function
>```
> in an error popup when using it as
> 
> 			SimpleTimer timer = new SimpleTimer(new BigDecimal("1"));
> 			layout.add(timer);
> 			timer.start();
> 			timer.addTimerEndEvent(ev-> Notification.show("Timer ended"));

Second message added more information: 
> I'm using Vaadin 21.0.0 with Spring boot 2.5.4.

**Comment by Antho1989** [comment]
Problem solved (at least avoided by commenting the vaadin.whitelisted-packages= in  application.properties

**Comment by paodb** [comment]
Hello @Antho1989 sorry for the delay on this. Instead of removing you could update the whitelisted property adding 
`com.flowingcode.vaadin.addons` to it as it's mentioned [here](https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters). It will look something like this:
 `vaadin.whitelisted-packages = com.vaadin,org.vaadin,dev.hilla,com.example.application,com.flowingcode.vaadin.addons`
