### ISSUE TITLE
Release for Vaadin 24

### ISSUE THREAD

**Issue by lipisak** [FlowingCode/SimpleTimerAddon#35]
Hello,
are you planning release for Vaadin 24?
I see commits with 24 support but it was not released yet, was it?

Thx

JS

**Comment by javier-godoy** [comment]
Hello. The current version (2.1.1) is already compatible with Vaadin 14 to 24 (demo at https://addonsv24.flowingcode.com/simple-timer/simple-timer). There was no need of releasing a new major version of the add-on.

**Comment by lipisak** [comment]
Oh, ok then. I'm closing this issue. Thank you🙂
